// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg1Nced4O8oqfFsJX3uiKJOuifm394iFA',
    appId: '1:455891302780:web:1400c1f13f1b2564284cf9',
    messagingSenderId: '455891302780',
    projectId: 'autisme-2e708',
    authDomain: 'autisme-2e708.firebaseapp.com',
    storageBucket: 'autisme-2e708.appspot.com',
    measurementId: 'G-JBPJCZPK80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLH25oKwzDUYRvjZsnD1Nf8ljxy0RfdLo',
    appId: '1:455891302780:android:f1b178ecaa48b2a7284cf9',
    messagingSenderId: '455891302780',
    projectId: 'autisme-2e708',
    storageBucket: 'autisme-2e708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwhUOrNA0fzfTrXBGASr_v7czuqmXnFJw',
    appId: '1:455891302780:ios:37833ba42ca28d49284cf9',
    messagingSenderId: '455891302780',
    projectId: 'autisme-2e708',
    storageBucket: 'autisme-2e708.appspot.com',
    iosBundleId: 'com.example.autisme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwhUOrNA0fzfTrXBGASr_v7czuqmXnFJw',
    appId: '1:455891302780:ios:ba851a4898d67f3e284cf9',
    messagingSenderId: '455891302780',
    projectId: 'autisme-2e708',
    storageBucket: 'autisme-2e708.appspot.com',
    iosBundleId: 'com.example.autisme.RunnerTests',
  );
}
